#pragma once
/*
#include<algorithm>
#include<any>
#include<array>
#include<cmath>
#include<iostream>
#include<random>
#include<xutility>
#include<algorithm>
#include<any>
#include<array>
#include<cmath>
#include<iostream>
#include<random>
#include<xutility>
#include<algorithm>
#include<any>
#include<array>
#include<cmath>
#include<iostream>
#include<random>
#include<xutility>
#include<algorithm>
#include<any>
#include<array>
#include<cmath>
#include<iostream>
#include<random>
#include<xutility>
*/